# Sourcing in zprofile, to make sure that it is done after /etc/profile
# https://wiki.archlinux.org/index.php/Zsh#Configuration_files

# echo "Sourcing in zprofile"

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

source ${DOTFILES}/zsh.d/path.sh

##
# Your previous /Users/galladi/.zprofile file was backed up as /Users/galladi/.zprofile.macports-saved_2024-08-14_at_16:08:24
##

# MacPorts Installer addition on 2024-08-14_at_16:08:24: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2024-08-14_at_16:08:24: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.

