# Sourcing in zprofile, to make sure that it is done after /etc/profile
# https://wiki.archlinux.org/index.php/Zsh#Configuration_files

# echo "Sourcing in zprofile"

# export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

source ${DOTFILES}/zsh.d/path.sh
