# Sourcing in zprofile, to make sure that it is done after /etc/profile
# https://wiki.archlinux.org/index.php/Zsh#Configuration_files

echo "Sourcing in zprofile"

# source ${DOTFILES}/zsh.d/path.sh
